### ISSUE TITLE
Fail to get a transparent background in Lottie editor

### ISSUE THREAD

**Issue by Lisavdmerwe** [Inventsable/LoadingIcons#1]
Hi,

I would like to use your cool wrench loader in our app. I used Lottie Editor to change the color of the wrench, but failed to make the enclosed sections transparent. Instead, they remain white.

See link: https://lottiefiles.com/share/xaXQfV

Is this something that could be changed from the original AE file?

**Comment by Inventsable** [comment]
Hello,

The construction of this animation was done through shapes and not masks, but both the background and "white" section should correspond to the CSS class ".anim-bg" or ".anim-mask". If you don't know the color of the bg in order to compensate and cannot manually set them to be the same, I would have to dig back into the source file and change this to be masking on the layer instead. This should be relatively easy but I may not be able to do so immediately.

See here for an example of setting the bg and "mask" (negative space) to the same color in style.css:

https://repl.it/@Inventsable/Wrench-Loading-Icons

**Comment by Inventsable** [comment]
Hi @Lisavdmerwe, I rebuilt the animation using only 3 shapes and masks in order to get you a transparent version. Unfortunately Lottie does not render it correctly:

![](https://thumbs.gfycat.com/CapitalSelfishCamel-size_restricted.gif)

I've reported this as an issue in the Lottie-web repo, but cannot give you a file which has only the wrench itself with a fill and everything else transparent (hence using multiple shapes the same color as the background in the original file) unless I receive some solution there:

https://github.com/airbnb/lottie-web/issues/1873

**Comment by Inventsable** [comment]
Hi @Lisavdmerwe,

I contacted the creator of Lottie about this graphical error and he's produced a new commit to lottie-web which solves it:

https://github.com/airbnb/lottie-web/issues/1873#issuecomment-555966782

I've verified the new file does work with lottie-web@5.5.10:

https://github.com/Inventsable/LoadingIcons/blob/master/wrenches/white.json

Note that LottieFiles has not been updated yet, so using their editor will still produce the graphical error until they update their dependencies. Regardless, if you want to change the color (and assuming you're targeting a web app) you can always lean on the CSS to achieve this:

```css
.anim-main {
  fill: #ff0000;
}
```

**Comment by Inventsable** [comment]
Hello, this should be resolved
